apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: openshift-gitops
spec:
  destination:
    namespace: argocd-test
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: argocd-openshift1/argocd-openshift1-main/wordpress/application-manifest/
    repoURL: https://github.com/ajisha-sb/argocd-openshift1
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
